/** Generated by scripts/build-dotted-logo.mjs. Do not edit. */
export const DOTTED_LOGO = {
  src: "/brand/logo-horizontal-dotted.svg",
  cols: 154,
  rows: 24,
  /** width / height of the generated field. */
  ratio: 6.4167,
} as const;

export const DOTTED_LOGOTYPE = {
  src: "/brand/logo-logotype-dotted.svg",
  cols: 196,
  rows: 24,
  /** width / height of the generated field. */
  ratio: 8.1667,
} as const;
